### ISSUE TITLE
Compaction is not happening

### ISSUE THREAD

**Issue by vinitshetty** [ahmadazizi/redis_timeseries_manager#3]
As you can see we have lot of raw data by ticks but 1m compaction has only one record and not getting updated at all same for 3m, 5m and so on.

![image](https://github.com/user-attachments/assets/3cdc609e-3d33-4ca5-a59e-35592aa9052a)
![image](https://github.com/user-attachments/assets/212e283b-cfcd-4c5d-9d03-09cee700828a)
![image](https://github.com/user-attachments/assets/19a7897e-56ad-48a3-a81a-9ca40647b193)
![image](https://github.com/user-attachments/assets/a830471a-a103-4ead-9258-5ffb6d3e5f29)

**Comment by ahmadazizi** [comment]
Do you store data on the default redis db(db index 0)?
As mentioned in the docs, redis has some bugs that compaction rules do not work on dbs other than 0

**Comment by vinitshetty** [comment]
You are right! Sorry I was not using db 0.
